Using the same method as before, we perform a logistic regression but using in this case
the encoded categorical data

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import pickle

In [2]:
import os 
path = ('/Users/gabriel/Documents/data')
os.chdir(path)

In [3]:
df = pd.read_csv('Last_preprocessing.csv')
df.head()

,A0_East Anglia,A0_East Midlands,A0_Greater London,A0_Non-Mainland UK,A0_North-East England,A0_North-West England,A0_Others,A0_Scotland,A0_South-East England,A0_South-West England,...,V10,V2,V3,V4,V5,V6,V7,V9,TP,Targets
0,0,0,0,0,0,0,0,0,0,0,...,-0.056761,0.269289,0.178104,-0.382676,0.155328,-0.032119,-0.558132,-0.308204,-0.593742,0
1,0,0,0,0,0,0,0,0,0,0,...,-0.056761,0.269289,-0.188684,-0.718096,1.751069,-0.032119,-0.074237,-0.731282,0.938918,1
2,0,0,0,0,0,0,0,0,1,0,...,-0.056761,-1.996511,0.104747,-0.889739,-0.482968,-0.032119,-0.074237,-0.901180,1.398619,1
3,0,0,0,0,0,0,0,0,0,0,...,-0.056761,0.269289,-0.115327,-0.331899,0.155328,-0.032119,-0.074237,-0.109436,1.081091,1
4,1,0,0,0,0,0,0,0,0,0,...,-0.056761,0.269289,-0.408757,-0.175274,-1.440413,-0.032119,0.167710,-0.140528,-0.658814,0

In [8]:
inputs = df.iloc[:,:-1]
inputs.head()

,A0_East Anglia,A0_East Midlands,A0_Greater London,A0_Non-Mainland UK,A0_North-East England,A0_North-West England,A0_Others,A0_Scotland,A0_South-East England,A0_South-West England,...,V1,V10,V2,V3,V4,V5,V6,V7,V9,TP
0,0,0,0,0,0,0,0,0,0,0,...,2.091244,-0.056761,0.269289,0.178104,-0.382676,0.155328,-0.032119,-0.558132,-0.308204,-0.593742
1,0,0,0,0,0,0,0,0,0,0,...,-0.941047,-0.056761,0.269289,-0.188684,-0.718096,1.751069,-0.032119,-0.074237,-0.731282,0.938918
2,0,0,0,0,0,0,0,0,1,0,...,-0.363468,-0.056761,-1.996511,0.104747,-0.889739,-0.482968,-0.032119,-0.074237,-0.901180,1.398619
3,0,0,0,0,0,0,0,0,0,0,...,0.575098,-0.056761,0.269289,-0.115327,-0.331899,0.155328,-0.032119,-0.074237,-0.109436,1.081091
4,1,0,0,0,0,0,0,0,0,0,...,-1.085442,-0.056761,0.269289,-0.408757,-0.175274,-1.440413,-0.032119,0.167710,-0.140528,-0.658814

In [10]:
targets = df['Targets']
targets.head()

0    0
1    1
2    1
3    1
4    0
Name: Targets, dtype: int64

In [11]:
x_train,x_test,y_train,y_test = train_test_split(inputs,targets,train_size = 0.8, random_state = 20)

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [12]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(517764, 63) (517764,)
(129442, 63) (129442,)

In [13]:
reg = LogisticRegression()

In [14]:
reg.fit(x_train,y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [15]:
print('Score prediction:',reg.score(x_train,y_train).round(3)*100)

Score prediction: 84.8

# Saving a Serialize version of the model

In [17]:
filename = 'logistic_model.sav'
pickle.dump(reg, open(filename, 'wb'))